#---------------------------------#
#      general configuration      #
#---------------------------------#
version: 1.0.{build}
os: Visual Studio 2019
configuration: Release
branches:
  only:
  - main

#---------------------------------#
#    environment configuration    #
#---------------------------------#
environment:
  my_variable:
    secure: NhOAZWl58l2RlmsMW0vbXzKZPf9TOrjC8BndGIYAgFBFQNfkORg7tFe6mhOU1XxF

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
    - dotnet restore Generator.sln
    - dotnet tool install --global dotnet-sonarscanner --version 5.0.4
    - dotnet sonarscanner begin /k:"Amitpnk_Hexagonal-architecture-ASP.NET-Core" /o:"amitpnk" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:my_variable"
build:
    project: Generator.sln
    verbosity: minimal
after_build:
    - dotnet sonarscanner end /d:"sonar.login=$env:my_sonartoken_encrypted"

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# test_script:
# - run-tests.cmd

#---------------------------------#
#    notification configuration   #
#---------------------------------#
notifications:
- provider: Email
  to:
  - amit.naik8103@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
